host880.procolix.com:
  user: yuna
  stage: production
  repository: git@gitlab.com:yuna.tmt/themoscowtimes.com.git
  branch: master
  deploy_path: /data/www
  assets_path: /data/share/www/public
  assets:
    - img
    - css
    - js