<?php return [
	'Actuarial Work, Pensions & Insurance',
	'Advertising, PR & Marketing',
	'Arts, Culture & Heritage',
	'Banking',
	'Buying, Selling, Retailing',
	'Charity & Development work',
	'Creative Industries',
	'Defence & Public Protection',
	'Education',
	'Engineering, Manufacturing & Construction',
	'Financial Management & Accountancy',
	'Government & Politics',
	'Healthcare & Psychology',
	'Hospitality & Events Management',
	'HR & Recruitment',
	'Information Technology',
	'Languages & TEFL',
	'Legal Services',
	'Management Consultancy',
	'Media',
	'Medical',
	'Natural Resources & Environment',
	'Performing Arts',
	'Publishing',
	'Psychology',
	'Scientific Research',
	'Social, Guidance, Community',
	'Transport & Logistics',
];