<?php return [
  'news' => 'News',
  'opinion' => 'Opinion',
  'meanwhile' => 'Meanwhile',
  'city' => 'Arts & Life',
  'business' => 'Business',
	'climate' => 'Climate',
	'diaspora' => 'The New Diaspora',
	'ukraine_war' => 'Ukraine War',
  'sponsored' => 'Sponsored',
  'russian' => 'Article in Russian',
  'indepth' => 'In-Depth',
	'lecture_series' => 'TMT Lecture Series',
  'other' => 'Other',
  'analysis' => 'Analysis',
];
